version: "3.8"

services:
  redis:
    image: redis:6.0.9-alpine
    container_name: checkoutaja_redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - checkoutaja_network

  postgesql:
    image: postgres:13-alpine
    container_name: checkoutaja_postgesql
    expose:
      - "5432"
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=checkoutaja_db
      - POSTGRES_HOST=5432
    command: -p 5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - checkoutaja_network

networks:
  checkoutaja_network:
    driver: bridge