// Code generated by MockGen. DO NOT EDIT.
// Source: pg_repository.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "github.com/dinorain/checkoutaja/internal/models"
	utils "github.com/dinorain/checkoutaja/pkg/utils"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockSellerPGRepository is a mock of SellerPGRepository interface.
type MockSellerPGRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSellerPGRepositoryMockRecorder
}

// MockSellerPGRepositoryMockRecorder is the mock recorder for MockSellerPGRepository.
type MockSellerPGRepositoryMockRecorder struct {
	mock *MockSellerPGRepository
}

// NewMockSellerPGRepository creates a new mock instance.
func NewMockSellerPGRepository(ctrl *gomock.Controller) *MockSellerPGRepository {
	mock := &MockSellerPGRepository{ctrl: ctrl}
	mock.recorder = &MockSellerPGRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSellerPGRepository) EXPECT() *MockSellerPGRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSellerPGRepository) Create(ctx context.Context, user *models.Seller) (*models.Seller, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(*models.Seller)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSellerPGRepositoryMockRecorder) Create(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSellerPGRepository)(nil).Create), ctx, user)
}

// DeleteById mocks base method.
func (m *MockSellerPGRepository) DeleteById(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteById", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteById indicates an expected call of DeleteById.
func (mr *MockSellerPGRepositoryMockRecorder) DeleteById(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteById", reflect.TypeOf((*MockSellerPGRepository)(nil).DeleteById), ctx, userID)
}

// FindAll mocks base method.
func (m *MockSellerPGRepository) FindAll(ctx context.Context, pagination *utils.Pagination) ([]models.Seller, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, pagination)
	ret0, _ := ret[0].([]models.Seller)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockSellerPGRepositoryMockRecorder) FindAll(ctx, pagination interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockSellerPGRepository)(nil).FindAll), ctx, pagination)
}

// FindByEmail mocks base method.
func (m *MockSellerPGRepository) FindByEmail(ctx context.Context, email string) (*models.Seller, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", ctx, email)
	ret0, _ := ret[0].(*models.Seller)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockSellerPGRepositoryMockRecorder) FindByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockSellerPGRepository)(nil).FindByEmail), ctx, email)
}

// FindById mocks base method.
func (m *MockSellerPGRepository) FindById(ctx context.Context, userID uuid.UUID) (*models.Seller, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", ctx, userID)
	ret0, _ := ret[0].(*models.Seller)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockSellerPGRepositoryMockRecorder) FindById(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockSellerPGRepository)(nil).FindById), ctx, userID)
}

// UpdateById mocks base method.
func (m *MockSellerPGRepository) UpdateById(ctx context.Context, user *models.Seller) (*models.Seller, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateById", ctx, user)
	ret0, _ := ret[0].(*models.Seller)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateById indicates an expected call of UpdateById.
func (mr *MockSellerPGRepositoryMockRecorder) UpdateById(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateById", reflect.TypeOf((*MockSellerPGRepository)(nil).UpdateById), ctx, user)
}
