DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS brands CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TYPE IF EXISTS role;
DROP TYPE IF EXISTS status;
DROP EXTENSION IF EXISTS citext CASCADE;